/**
 * Service Worker Caching Configuration
 *
 * This module defines the caching strategies used by the service worker.
 * The actual service worker is generated by vite-plugin-pwa using Workbox.
 *
 * Caching Strategies:
 * - CacheFirst: Best for static assets that rarely change (fonts, CDN resources)
 * - StaleWhileRevalidate: Good balance for assets that may update (images, same-origin)
 * - NetworkFirst: For data that should be fresh but can fallback to cache (API calls)
 * - NetworkOnly: For sensitive data that should never be cached (payments, auth)
 *
 * @see https://developer.chrome.com/docs/workbox/modules/workbox-strategies/
 */

/**
 * Cache names used by the service worker
 */
export const CACHE_NAMES = {
  // Precache - static assets bundled with the app
  PRECACHE: 'workbox-precache-v2',

  // Runtime caches
  GOOGLE_FONTS_STYLESHEETS: 'google-fonts-stylesheets',
  GOOGLE_FONTS_WEBFONTS: 'google-fonts-webfonts',
  CDN: 'cdn-cache',
  GITHUB_AVATARS: 'github-avatars-cache',
  EXTERNAL_IMAGES: 'external-images-cache',
  CONVEX_API: 'convex-api-cache',
  LOCAL_ASSETS: 'local-assets-cache',
  SAME_ORIGIN: 'same-origin-cache',
} as const

export type CacheName = (typeof CACHE_NAMES)[keyof typeof CACHE_NAMES]

/**
 * Cache configuration with TTL and max entries
 */
export interface CacheConfig {
  name: CacheName
  maxEntries: number
  maxAgeSeconds: number
  strategy: 'CacheFirst' | 'StaleWhileRevalidate' | 'NetworkFirst' | 'NetworkOnly'
}

/**
 * Cache configurations for each cache type
 */
export const CACHE_CONFIGS: Record<string, CacheConfig> = {
  googleFontsStylesheets: {
    name: CACHE_NAMES.GOOGLE_FONTS_STYLESHEETS,
    maxEntries: 10,
    maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
    strategy: 'CacheFirst',
  },
  googleFontsWebfonts: {
    name: CACHE_NAMES.GOOGLE_FONTS_WEBFONTS,
    maxEntries: 30,
    maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
    strategy: 'CacheFirst',
  },
  cdn: {
    name: CACHE_NAMES.CDN,
    maxEntries: 100,
    maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
    strategy: 'CacheFirst',
  },
  githubAvatars: {
    name: CACHE_NAMES.GITHUB_AVATARS,
    maxEntries: 100,
    maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
    strategy: 'CacheFirst',
  },
  externalImages: {
    name: CACHE_NAMES.EXTERNAL_IMAGES,
    maxEntries: 200,
    maxAgeSeconds: 60 * 60 * 24 * 14, // 14 days
    strategy: 'StaleWhileRevalidate',
  },
  convexApi: {
    name: CACHE_NAMES.CONVEX_API,
    maxEntries: 50,
    maxAgeSeconds: 60 * 5, // 5 minutes
    strategy: 'NetworkFirst',
  },
  localAssets: {
    name: CACHE_NAMES.LOCAL_ASSETS,
    maxEntries: 100,
    maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
    strategy: 'CacheFirst',
  },
  sameOrigin: {
    name: CACHE_NAMES.SAME_ORIGIN,
    maxEntries: 100,
    maxAgeSeconds: 60 * 60 * 24, // 1 day
    strategy: 'StaleWhileRevalidate',
  },
}

/**
 * Get all cache names managed by the service worker
 */
export function getAllCacheNames(): CacheName[] {
  return Object.values(CACHE_NAMES)
}

/**
 * Clear all runtime caches (not precache)
 * Useful for forcing fresh data or debugging
 */
export async function clearRuntimeCaches(): Promise<void> {
  if (typeof caches === 'undefined') {
    console.warn('[SW Cache] Cache API not available')
    return
  }

  const cacheNames = await caches.keys()
  const runtimeCacheNames = cacheNames.filter((name) => !name.includes('precache'))

  await Promise.all(runtimeCacheNames.map((name) => caches.delete(name)))
  console.log('[SW Cache] Cleared runtime caches:', runtimeCacheNames)
}

/**
 * Clear a specific cache by name
 */
export async function clearCache(cacheName: CacheName): Promise<boolean> {
  if (typeof caches === 'undefined') {
    console.warn('[SW Cache] Cache API not available')
    return false
  }

  const deleted = await caches.delete(cacheName)
  if (deleted) {
    console.log(`[SW Cache] Cleared cache: ${cacheName}`)
  }
  return deleted
}

/**
 * Get cache storage usage statistics
 */
export async function getCacheStats(): Promise<{
  caches: Array<{ name: string; size: number; entries: number }>
  totalSize: number
  totalEntries: number
}> {
  if (typeof caches === 'undefined') {
    return { caches: [], totalSize: 0, totalEntries: 0 }
  }

  const cacheNames = await caches.keys()
  const stats: Array<{ name: string; size: number; entries: number }> = []

  for (const name of cacheNames) {
    const cache = await caches.open(name)
    const keys = await cache.keys()
    let size = 0

    // Estimate size by checking response sizes
    for (const request of keys) {
      const response = await cache.match(request)
      if (response) {
        const blob = await response.clone().blob()
        size += blob.size
      }
    }

    stats.push({ name, size, entries: keys.length })
  }

  const totalSize = stats.reduce((sum, cache) => sum + cache.size, 0)
  const totalEntries = stats.reduce((sum, cache) => sum + cache.entries, 0)

  return { caches: stats, totalSize, totalEntries }
}

/**
 * Check if a URL would be cached based on our caching rules
 */
export function wouldBeCached(url: string): {
  cached: boolean
  cacheName?: CacheName
  strategy?: string
} {
  const urlObj = new URL(url, window.location.origin)

  // Google Fonts stylesheets
  if (/^https:\/\/fonts\.googleapis\.com\/.*/i.test(url)) {
    return { cached: true, cacheName: CACHE_NAMES.GOOGLE_FONTS_STYLESHEETS, strategy: 'CacheFirst' }
  }

  // Google Fonts webfonts
  if (/^https:\/\/fonts\.gstatic\.com\/.*/i.test(url)) {
    return { cached: true, cacheName: CACHE_NAMES.GOOGLE_FONTS_WEBFONTS, strategy: 'CacheFirst' }
  }

  // CDN resources
  if (/^https:\/\/cdn\.jsdelivr\.net\/.*/i.test(url)) {
    return { cached: true, cacheName: CACHE_NAMES.CDN, strategy: 'CacheFirst' }
  }

  // GitHub avatars
  if (/^https:\/\/avatars\.githubusercontent\.com\/.*/i.test(url)) {
    return { cached: true, cacheName: CACHE_NAMES.GITHUB_AVATARS, strategy: 'CacheFirst' }
  }

  // External images
  if (/^https:\/\/.*\.(png|jpg|jpeg|gif|webp|svg)$/i.test(url)) {
    return {
      cached: true,
      cacheName: CACHE_NAMES.EXTERNAL_IMAGES,
      strategy: 'StaleWhileRevalidate',
    }
  }

  // Convex API
  if (/^https:\/\/.*\.convex\.cloud\/.*/i.test(url)) {
    return { cached: true, cacheName: CACHE_NAMES.CONVEX_API, strategy: 'NetworkFirst' }
  }

  // Stripe API - never cached
  if (/^https:\/\/.*\.stripe\.com\/.*/i.test(url)) {
    return { cached: false }
  }

  // OpenAI API - never cached
  if (/^https:\/\/api\.openai\.com\/.*/i.test(url)) {
    return { cached: false }
  }

  // Local assets
  if (/\/assets\/.*/i.test(urlObj.pathname)) {
    return { cached: true, cacheName: CACHE_NAMES.LOCAL_ASSETS, strategy: 'CacheFirst' }
  }

  // Same origin
  if (urlObj.origin === window.location.origin) {
    return { cached: true, cacheName: CACHE_NAMES.SAME_ORIGIN, strategy: 'StaleWhileRevalidate' }
  }

  return { cached: false }
}

/**
 * Format bytes to human readable string
 */
export function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`
}
